### ISSUE TITLE
Improve sync performance

### ISSUE THREAD

**Issue by alexandrepiveteau** [markdown-party/kotlin-echo#94]
Following the sync algorithm rewrite to use the new data structures, a few changes could be made to the **protocol implementation** and to the **data structures** :

+ [x] `ChangeScope` recycling to avoid the extra allocation on each `backward` call on event insertion (see #95).
+ [x] `ArrayQueue` in `Protocol.outgoing.kt` could only be filled up again with new events once it's empty (see #120).
+ [x] Arrays in `Protocol.outgoing.kt` could possibly be binary searched (see #120).

---

+ [x] `MutableEventLog` could feature a "lower bound" of available events, and a O(n) algorithm could be designed to find the lower bound of events to search for in the log, depending on the available credits, the last sent acknowledgements, and the available events.
+ [x] `MutableEventLog` could support some per-site logs of events, for faster iteration. This would likely duplicate the amount of space needed to store the events, but offer considerably faster sync performance. Additionally, changes do not need to be stored.
+ [ ] #121
